version: "3.8"
services:
  frontend:
    image: techos/web:latest
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_TELEMETRY_DISABLED: 1
        CMS_ENDPOINT: http://host.docker.internal:13371
        CMS_API_KEY: 20832abfa12e272e6e3fdd2e7ee312f1e0d5300ef71ae876eab37aa539e7b3e58c7018493570a9e0792dc921e70d450505a06a5b4335e34c93772b96aaa1cfa8dd7fc2a700cd5901da7ec6f84fb5aa6ad3ec93df0df72e24bef6ac73a738a754b0507f63fbe1e9f3d22b27e57461e662520d3f37b0e7ad9ca2d82db4a9b1b886
        NEXT_PUBLIC_FRONT_URL: http://localhost:30001
        NEXT_PUBLIC_BUCKET_HOST: asset-techos-prod.s3.fr-par.scw.cloud
        JWT_KEY: secret
        BUILD_MODE: true
    env_file:
      - .env
    ports:
      - 30001:3000
    networks:
      - techos
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "docker.for.win.host.internal:host-gateway"
networks:
  techos:
    driver: bridge
volumes:
  volume_data:
    driver: local
